### ISSUE TITLE
Rotating (Blank) ref?= or s1?=

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#108]
In your message on skype, you mentioned the following:

If ref or s1 does not exist - https://mcaprotools.com/whatismca/ then it will show the normal page with no referring user. 

.
.
.

However, can we default a "VIP User" (manual role added to user by admin) anytime there is a blank ?ref= or ?s1= so that every time the page refreshes / or the url is visited without a "ref" or "s1" it will apply the "VIP User" to the end of the URL.

- url?ref=vipuser1
- {refresh the page - still blank]
- url?ref=vipuser2
- {refresh the page - still blank]
- url?ref=felontofortune
- {refresh the page - still blank]
- url?ref=sgerritse

Etc...

This allow for all our VIP users to get credit for "blank" referrals, but we obviously dont want it to go to just one person -we want to rotate the between the VIP Users”.

.
.
.
Lastly - Can it be applied discreetly? Not in the actual URL - just the page knows there is no ref / s1 data. To load VIPUSER1 instead.

**Comment by tarundhanwani** [comment]
Hi, this is ready for your review. I've also made it so that the ref/s1 is applied discreetly for vip users.

Right now I've set only 3 accounts as vip user, one is ptadmin, the other felontofortune and lastly testuser. The new VIP User role can be applied by going to WP Admin > Users > hover over a user and click on 'Capabilities'. Then on the right select VIP User checkbox.
![screen shot 2017-05-11 at 9 38 58 am](https://cloud.githubusercontent.com/assets/3523102/25928233/baa2083a-362d-11e7-9da8-dd8bf500fc27.png)



Thanks
