### ISSUE TITLE
Invite Page - View Permissions

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#71]
https://mcaprotools.com/invite/
- When logged into a user "felontofortune / asher187", I can not view this page. It just redirects me to the "dashboard". The user should still be able to view this page even if they are logged in.

- Can not view the "Invite Page" as a guest. Guest(s) should certainly be able to view this page.

**Comment by tarundhanwani** [comment]
Hi @sgerritse I've fixed the redirect and permission issue, the issue was a redirect code was present in the invite page template, something like if user is logged in redirect to /dashboard.

I then checked the page link https://mcaprotools.com/invite/ , it redirects users to the homepage because the homepage page https://mcaprotools.com/wp-admin/post.php?post=1467&action=edit is actually the /invite page hence it redirects to the homepage. Is this the proper scenario or should the /invite page be separate/not redirect to the homepage? If so then what I'll do is create another page just for the /invite page.

Thanks
